### ISSUE TITLE
Implement statistics functions

### ISSUE THREAD

**Issue by namseonu** [oss-inc/mowa-frontend-android#3]
**To-do list**
- [x] check daily activities statistics
- [x] check monthly activities statistics
- [ ] check all activities statistics
- [ ] initialize some activity the user wants

<br>

**With caution**
